[project]
name = "215-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "alembic>=1.14.1",
    "pandas>=2.0.3",
    "plotly>=6.5.0",
    "psycopg2>=2.9.10",
]
